---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    image: registry.gitlab.com/stremio-add-ons/annatar:latest
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: debug
      JACKETT_URL: "http://85.61.137.47:9117"
      JACKETT_API_KEY: "sro9ybsw7bign818vygiu8t4rwrtewke"
      JACKETT_MAX_RESULTS: "10" # max results from jackett search
      JACKETT_TIMEOUT: "10" # max time spent searching per indexer.
      JACKETT_INDEXERS: "Il Corsaro Nero,ItaTorrents,MIRCrew"
      LISTEN_PORT: "8000"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
